import {Inter_Tight } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const fonts = Inter_Tight({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Logistic website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fonts.className}`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
